apiVersion: v1
entries:
  agent-control-plane:
  - apiVersion: v2
    appVersion: 0.7.3-SNAPSHOT
    created: "2023-01-26T11:31:29.602073+01:00"
    description: Agent-Enabled EDC Control-Plane - Eclipse DataSpaceConnector administration
      layer with Agent Protocols extensions
    digest: ae99de7cd71e66485307a2f0d4ff2356bd4a01d74b158198c785447df1c82f43
    home: https://github.com/catenax-ng/product-knowledge/infrastructure/charts/agent-control-plane
    icon: https://catenax-ng.github.io/product-knowledge/img/logo.svg
    maintainers:
    - name: Catena-X Knowledge Agents Team
    name: agent-control-plane
    type: application
    urls:
    - https://catenax-ng.github.io/product-knowledge/infrastructure/agent-control-plane-0.7.3-SNAPSHOT.tgz
    version: 0.7.3-SNAPSHOT
  agent-data-plane:
  - apiVersion: v2
    appVersion: 0.7.3-SNAPSHOT
    created: "2023-01-26T11:31:29.603161+01:00"
    description: Agent-Enabled EDC Data-Plane - Eclipse DataSpaceConnector data layer
      with Agent Protocol Extensions
    digest: e1fe9978e0725fa65fc74f7bd2ad6719c446228863035938245469d5e3072945
    home: https://github.com/catenax-ng/product-knowledge/infrastructure/charts/agent-data-plane
    icon: https://catenax-ng.github.io/product-knowledge/img/logo.svg
    maintainers:
    - name: Catena-X Knowledge Agents Team
    name: agent-data-plane
    type: application
    urls:
    - https://catenax-ng.github.io/product-knowledge/infrastructure/agent-data-plane-0.7.3-SNAPSHOT.tgz
    version: 0.7.3-SNAPSHOT
  provisioning-agent:
  - apiVersion: v2
    appVersion: 0.7.3-SNAPSHOT
    created: "2023-01-26T11:31:29.604126+01:00"
    description: Catena-X Provisioning Agent - Knowledge-Agents Compatible Data Binding
      Layer
    digest: 1d69501990a2d1226d8b6936ca549b7b29b542e199cc0dd708387aeef154c2b9
    home: https://github.com/catenax-ng/product-knowledge/infrastructure/charts/provisioning-agent
    icon: https://catenax-ng.github.io/product-knowledge/img/logo.svg
    maintainers:
    - name: Catena-X Knowledge Agents Team
    name: provisioning-agent
    type: application
    urls:
    - https://catenax-ng.github.io/product-knowledge/infrastructure/provisioning-agent-0.7.3-SNAPSHOT.tgz
    version: 0.7.3-SNAPSHOT
  remoting-agent:
  - apiVersion: v2
    appVersion: 0.7.3-SNAPSHOT
    created: "2023-01-26T11:31:29.605037+01:00"
    description: Catena-X Remoting Agent - Knowledge-Agents Compatible API Binding
      Layer
    digest: 4057d534aa553651ae457a68c1b8443680579a399064361e819d8a966d1ce018
    home: https://github.com/catenax-ng/product-knowledge/infrastructure/charts/remoting-agent
    icon: https://catenax-ng.github.io/product-knowledge/img/logo.svg
    maintainers:
    - name: Catena-X Knowledge Agents Team
    name: remoting-agent
    type: application
    urls:
    - https://catenax-ng.github.io/product-knowledge/infrastructure/remoting-agent-0.7.3-SNAPSHOT.tgz
    version: 0.7.3-SNAPSHOT
generated: "2023-01-26T11:31:29.598527+01:00"
