apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-config
data:
  portal.env: |-
{{- .Files.Get "config/int.env" | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
        - name: portal
          image: ghcr.io/catenax-ng/product-knowledge/portal:0.0.1
          imagePullPolicy: Always
          ports:
          env:
          volumeMounts:
            - name: portal-config
              mountPath: /app/.env
              subPath: portal.env
      volumes:
        - name: portal-config
          configMap:
            name: portal-config
---
apiVersion: v1
kind: Service
metadata:
  name: portal
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: portal
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/x-forwarded-prefix: "/portal"
    nginx.org/mergeable-ingress-type: minion
spec:
  rules:
    - host: hey.int.demo.catena-x.net
      http:
        paths:
          - path: /portal(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: portal
                port:
                  number: 80
