apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-frontend
  namespace: {{ .Values.namespace }}
  annotations:
    container.apparmor.security.beta.kubernetes.io/tiera-backend: default
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: consumer-frontend
  template:
    metadata:
      labels:
        app: consumer-frontend
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 10000
        runAsGroup: 30000
        fsGroup: 30000
        seccompProfile:
           type: RuntimeDefault
      containers:
        - name: ux-frontend
          image: ghcr.io/catenax-ng/product-knowledge/ux:{{.Values.version}}
          imagePullPolicy: Always
          securityContext:
            capabilities:
              drop:
                - all
              add: ['NET_BIND_SERVICE']
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
          ports:
            - containerPort: 8080 # http
          resources:
           requests:
            cpu: 500m
            memory: 1Gi
           limits:
            cpu: 500m
            memory: 1Gi
          startupProbe:
            failureThreshold: 18
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            periodSeconds: 300
            successThreshold: 1
            timeoutSeconds: 5        
          env:
            - name: REACT_APP_SKILL_CONNECTOR_DATA
              value: https://{{ .Values.ingress.host }}/consumer-edc-data/BPNL00000003CQI9
            - name: REACT_APP_SKILL_CONNECTOR_CONTROL
              value: https://{{ .Values.ingress.host }}/oem-edc-control/BPNL00000003COJN
            - name: REACT_APP_SKILL_CONNECTOR_AUTH_HEADER_KEY
              value: X-Api-Key
            - name: REACT_APP_SKILL_CONNECTOR_AUTH_HEADER_VALUE
              value: {{ .Values.security.xApiKey }}
            - name: REACT_APP_SKILL_BACKEND
              value: https://{{ .Values.ingress.host }}/consumer-frontend/webvowl/index.html
            - name: REACT_APP_SKILL_GITHUB_ONTOLOGYHUB
              value: https://api.github.com/repos/catenax-ng/product-knowledge/contents/ontology?ref={{ .Values.dataspace.ontologyRef }}
            - name: REACT_APP_FOLDER
              value: /consumer-frontend
          volumeMounts:
      volumes:
---
apiVersion: v1
kind: Service
metadata:
  name: consumer-frontend
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: consumer-frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: consumer-frontend-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.issuer }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://knowledge.dev.demo.catena-x.net,http://localhost:3000,https://admin-shell-io.com"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, PUT, POST, DELETE, PATCH, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Host,DNT,X-Api-Key,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization"
    nginx.ingress.kubernetes.io/x-forwarded-prefix: "/consumer-frontend"
    nginx.org/mergeable-ingress-type: minion
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /consumer-frontend(.*)
            pathType: Prefix
            backend:
              service:
                name: consumer-frontend
                port:
                  number: 8080
