---
apiVersion: v1
data:
  azurestorageaccountname: {{ .Values.security.backupsName }} 
  azurestorageaccountkey: {{ .Values.security.backupsKey }} 
kind: {{ .Values.security.htpasswdtype }}
metadata:
  name: oem-backend-storage
  namespace: {{ .Values.namespace }}
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oem-backend-config
  namespace: {{ .Values.namespace }}
data:
  dremio.conf: |-
    paths: {
      # the local path for dremio to store data.
      local: ${DREMIO_HOME}"/data"

      # the distributed path Dremio data including job results, downloads, uploads, etc
      #dist: "pdfs://"${paths.local}"/pdfs"
    }

    services: {
      coordinator.enabled: true,
      coordinator.master.enabled: true,
      executor.enabled: true,
      flight.use_session_service: true,
      conduit.port: 37877
    } 

    registration.publish-host: "oem-backend"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oem-backend
  namespace: {{ .Values.namespace }}
  annotations:
    container.apparmor.security.beta.kubernetes.io/oem-provider-agent: default
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: oem-backend
  template:
    metadata:
      labels:
        app: oem-backend
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 10000
        runAsGroup: 30000
        fsGroup: 30000
        seccompProfile:
           type: RuntimeDefault
      containers:
        - name: oem-backend
          image: ghcr.io/catenax-ng/product-knowledge/virtualizer-dremio:{{.Values.version}}
          imagePullPolicy: Always
          securityContext:
            capabilities:
              drop:
                - all
              add: ['NET_BIND_SERVICE']
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
          ports:
            - containerPort: 2181   # Zookeeper
            - containerPort: 9047   # Web
            - containerPort: 31010  # JDBC
            - containerPort: 32010  # Arrow
            - containerPort: 37877  # Conduit
            - containerPort: 45678  # Dremio Exec
          resources:
           requests:
            cpu: 500m
            memory: 4Gi
           limits:
            cpu: 500m
            memory: 4Gi
          startupProbe:
            failureThreshold: 18
            httpGet:
              path: /
              port: 9047
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /
              port: 9047
              scheme: HTTP
            periodSeconds: 300
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 2
            httpGet:
              path: /
              port: 9047
              scheme: HTTP
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 5        
          env:
#            - name: JAVA_TOOL_OPTIONS
#              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8090"
          volumeMounts:
            - name: data
              mountPath: /opt/dremio/data
            - name: oem-backend-config
              mountPath: /opt/dremio/conf/dremio.conf
              subPath: dremio.conf
              readOnly: true
      volumes:
        - name: data
          size: "4Gi"
        - name: oem-backend-config
          configMap:
            name: oem-backend-config
---
apiVersion: v1
kind: Service
metadata:
  name: oem-backend
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 2181
      name: zookeeper
      targetPort: 2181
    - port: 9047
      name: web
      targetPort: 9047
    - port: 31010
      name: jdbc
      targetPort: 31010
    - port: 32010
      name: arrow
      targetPort: 32010
    - port: 37877
      name: conduit
      targetPort: 37877
    - port: 45678
      name: execute
      targetPort: 45678
  selector:
    app: oem-backend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oem-backend-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.issuer }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://knowledge.dev.demo.catena-x.net, http://localhost:3000"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, PUT, POST, DELETE, PATCH, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Host,DNT,X-Api-Key,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization"
    nginx.ingress.kubernetes.io/x-forwarded-prefix: "/oem-backend"
    nginx.org/mergeable-ingress-type: master
    # type of authentication
    #nginx.ingress.kubernetes.io/auth-type: basic
    # name of the secret that contains the user/password definitions
    #nginx.ingress.kubernetes.io/{{ .Values.security.authType }}: oem-provider-auth
    # message to display with an appropriate context why the authentication is required
    #nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - OEM'
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.oemHost }}
      secretName: tls-knowledge-oem
  rules:
    - host: {{ .Values.ingress.oemHost }}
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: oem-backend
                port:
                  number: 9047
