apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-backend
  namespace: {{ .Values.namespace }}
  annotations:
    container.apparmor.security.beta.kubernetes.io/tiera-backend: default
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: service-backend
  template:
    metadata:
      labels:
        app: service-backend
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 10000
        runAsGroup: 30000
        fsGroup: 30000
        seccompProfile:
           type: RuntimeDefault
      containers:
        - name: tiera-backend
          image: ghcr.io/catenax-ng/product-knowledge/prognosis:{{ .Values.version }}
          imagePullPolicy: Always
          securityContext:
            capabilities:
              drop:
                - all
              add: ['NET_BIND_SERVICE']
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 5005 # API
          resources:
           requests:
            cpu: 500m
            memory: 256Mi
           limits:
            cpu: 500m
            memory: 256Mi
          startupProbe:
            failureThreshold: 18
            httpGet:
              path: /docs
              port: 5005
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /docs
              port: 5005
              scheme: HTTP
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /docs
              port: 5005
              scheme: HTTP
            periodSeconds: 300
            successThreshold: 1
            timeoutSeconds: 5        
          env:
          volumeMounts:
      volumes:
---
apiVersion: v1
kind: Service
metadata:
  name: service-backend
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 5005
      targetPort: 5005
  selector:
    app: service-backend
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tiera-remoting-config
  namespace: {{ .Values.namespace }}
data:
  application.properties: |-
    cloud.accessKey=
    cloud.secretKey=  
    edc.apiwrapper.username=
    edc.apiwrapper.password=
    security.api.username={{ .Values.security.backendUser }}
    security.api.password={{ .Values.security.backendPwd }}
    rawdatadb.username={{ .Values.postgresql.auth.username }}
    rawdatadb.password={{ .Values.postgresql.auth.password }}
    ruldb.username={{ .Values.postgresql.auth.username }}
    ruldb.password={{ .Values.postgresql.auth.password }}
    server.port=35553
    spring.application.name=rulbackendservice
    spring.jpa.open-in-view=false
    edc.apiwrapper.submodelPath=api/service
    edc.apiwrapper.submodel=submodel
    edc.apiwrapper.providerEdcUrlKey=provider-connector-url
    security.api.endpoints.noauth.global=false
    security.api.endpoints.noauth.callbacks=true
    ruldb.drivername=org.postgresql.Driver
    ruldb.show-sql=false
    ruldb.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    ruldb.hibernate.hbm2ddl.auto=update
    ruldb.url=jdbc:postgresql://postgresql/{{ .Values.postgresql.auth.database }}
    rawdatadb.drivername=org.postgresql.Driver
    rawdatadb.show-sql=false
    rawdatadb.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    rawdatadb.hibernate.hbm2ddl.auto=update
    rawdatadb.url=jdbc:postgresql://postgresql/{{ .Values.postgresql.auth.database }}
    cloud.endpoint=
    cloud.region=
    cloud.bucket=test
    cloud.inputFile.bucketName=testbucket
    cloud.inputFile.key=testfile
    edc.apiwrapper.url=
    requester.rulservice.classification=RemainingUsefulLifeResult
    supplier.rulservice.endpoint=http://localhost:8898
    supplier.rulservice.bpn=BPNL0000000DUMMY
    supplier.rulservice.inputAssetId=urn:uuid:xxxx
    supplier.rulservice.respondAssetId=urn:pilot:service:RemainingUsefulLifeResultNotification
    supplier.rulservice.classification=RemainingUsefulLifePredictor
    edc.bpn=BPNL0000000DUMMY
    edc.endpoint=
    spring.config.import=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rul-backend
  namespace: {{ .Values.namespace }}
  annotations:
    container.apparmor.security.beta.kubernetes.io/tiera-backend: default
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: rul-backend
  template:
    metadata:
      labels:
        app: rul-backend
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 10000
        runAsGroup: 30000
        fsGroup: 30000
        seccompProfile:
           type: RuntimeDefault
      containers:
        - name: rul-backend
          image: ghcr.io/catenax-ng/product-oem-rul-backend:release
          imagePullPolicy: Always
          securityContext:
            capabilities:
              drop:
                - all
              add: ['NET_BIND_SERVICE']
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 35553 # API
          resources:
           requests:
            cpu: 500m
            memory: 512Mi
           limits:
            cpu: 500m
            memory: 512Mi
          startupProbe:
            failureThreshold: 18
            httpGet:
              httpHeaders:
                - name: Authorization
                  value: {{ printf "Basic %s" (printf "%s:%s" .Values.security.backendUser .Values.security.backendPwd | b64enc) }}
              path: /
              port: 35553
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 3
            httpGet:
              httpHeaders:
                - name: Authorization
                  value: {{ printf "Basic %s" (printf "%s:%s" .Values.security.backendUser .Values.security.backendPwd | b64enc) }}
              path: /
              port: 35553
              scheme: HTTP
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              httpHeaders:
                - name: Authorization
                  value: {{ printf "Basic %s" (printf "%s:%s" .Values.security.backendUser .Values.security.backendPwd | b64enc) }}
              path: /
              port: 35553
              scheme: HTTP
            periodSeconds: 300
            successThreshold: 1
            timeoutSeconds: 5        
          env:
          volumeMounts:
            - name: tiera-remoting-config
              mountPath: /opt/app/application-rulbackendservice.properties
              subPath: application.properties
              readOnly: true
      volumes:
        - name: tiera-remoting-config
          configMap:
            name: tiera-remoting-config
---
apiVersion: v1
kind: Service
metadata:
  name: rul-backend
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 35553
      targetPort: 35553
  selector:
    app: rul-backend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tiera-backend-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.issuer }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://knowledge.dev.demo.catena-x.net, http://localhost:3000"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, PUT, POST, DELETE, PATCH, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Host,DNT,X-Api-Key,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization"
    nginx.ingress.kubernetes.io/x-forwarded-prefix: "/tiera-backend"
    nginx.org/mergeable-ingress-type: minion
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /tiera-backend/?(.*)
            pathType: Prefix
            backend:
              service:
                name: service-backend
                port:
                  number: 5005
          - path: /tiera-backend2/?(.*)
            pathType: Prefix
            backend:
              service:
                name: rul-backend
                port:
                  number: 35553
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tiera-remoting-agent-config
  namespace: {{ .Values.namespace }}
data:
  health.ttl: |-
{{- .Files.Get "tiera/resources/rdf4j/repositories/health/config.ttl" | nindent 4 }}
  prognosis.ttl: |-
{{- .Files.Get "tiera/resources/rdf4j/repositories/prognosis/config.ttl" | nindent 4 }}
  rul.ttl: |-
{{- .Files.Get "tiera/resources/rdf4j/repositories/rul/config.ttl" | nindent 4 }}
  logback.xml: |-
{{- .Files.Get "tiera/resources/rdf4j/conf/logback.xml" | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiera-remoting-agent
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: tiera-remoting-agent
  template:
    metadata:
      labels:
        app: tiera-remoting-agent
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 10000
        runAsGroup: 30000
        fsGroup: 30000
        seccompProfile:
           type: RuntimeDefault
      containers:
        - name: tiera-remoting-agent
          image: tractusx/remoting-agent:1.11.16-SNAPSHOT
          imagePullPolicy: Always
          securityContext:
            capabilities:
              drop:
                - all
              add: ['NET_BIND_SERVICE']
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
          ports:
            - containerPort: 8081 # API
          resources:
           requests:
            cpu: 500m
            memory: 512Mi
           limits:
            cpu: 500m
            memory: 512Mi
          startupProbe:
            failureThreshold: 18
            httpGet:
              path: /rdf4j-server/protocol
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /rdf4j-server/protocol
              port: 8081
              scheme: HTTP
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /rdf4j-server/protocol
              port: 8081
              scheme: HTTP
            periodSeconds: 300
            successThreshold: 1
            timeoutSeconds: 5        
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "" #"-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8090"
          volumeMounts:
            - name: tiera-remoting-agent-config
              mountPath: /var/rdf4j/server/repositories/prognosis/config.ttl
              subPath: prognosis.ttl
              readOnly: true
            - name: tiera-remoting-agent-config
              mountPath: /var/rdf4j/server/repositories/health/config.ttl
              subPath: health.ttl
              readOnly: true
            - name: tiera-remoting-agent-config
              mountPath: /var/rdf4j/server/repositories/rul/config.ttl
              subPath: rul.ttl
              readOnly: true
            - name: tiera-remoting-agent-config
              mountPath: /var/rdf4j/server/conf/logback.xml
              subPath: logback.xml
              readOnly: true
      volumes:
        - name: tiera-remoting-agent-config
          configMap:
            name: tiera-remoting-agent-config
---
apiVersion: v1
kind: Service
metadata:
  name: tiera-remoting-agent
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: tiera-remoting-agent
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tiera-remoting-agent-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.issuer }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://knowledge.dev.demo.catena-x.net, http://localhost:3000"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, PUT, POST, DELETE, PATCH, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Host,DNT,X-Api-Key,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization"
    nginx.ingress.kubernetes.io/x-forwarded-prefix: "/tiera-remoting-agent"
    nginx.org/mergeable-ingress-type: minion
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /tiera-remoting-agent(.*)
            pathType: Prefix
            backend:
              service:
                name: tiera-remoting-agent
                port:
                  number: 8081