apiVersion: v1
kind: ConfigMap
metadata:
  name: tiera-control-plane-config
  namespace: {{ .Values.namespace }}
data:
  configuration.properties: |-
    web.http.default.port=8080
    web.http.default.path=/api
    web.http.management.port=8181
    web.http.management.path=/management
    web.http.control.port=9999
    web.http.control.path=/control
    web.http.protocol.port=8282
    web.http.protocol.path=/api/v1/dsp
    web.http.metrics.port=9998
    web.http.metrics.path=/metrics
    
    tractusx.api.observability.allow-insecure=true
    web.http.observability.port=8081
    web.http.observability.path=/observability
  
    edc.api.auth.key={{ .Values.security.xApiKey }}
    
    edc.fs.config=/connector-config/configuration.properties
    edc.hostname={{ .Values.ingress.host }}
    
    # This is send as the audience to outgoing ids messages/tokens
    edc.dsp.callback.address=https://{{ .Values.ingress.host }}/tiera-edc-control/{{ .Values.dataspace.bpnTier1 }}/api/v1/dsp
    edc.participant.id=BPNL00000003CPIY
    
    edc.oauth.client.id={{ .Values.dataspace.dapsClientIdTier1 }}
    edc.oauth.private.key.alias={{ .Values.dataspace.privateKeyAliasTier1 }}
    edc.oauth.provider.audience=idsc:IDS_CONNECTORS_ALL
    edc.oauth.endpoint.audience=https://{{ .Values.ingress.host }}/tiera-edc-control/{{ .Values.dataspace.bpnTier1 }}/api/v1/ids/data

    edc.data.encryption.algorithm=AES
    edc.data.encryption.keys.alias=tiera-symmetric-key
    
    edc.oauth.provider.jwks.url={{ .Values.security.dapsUrl }}/.well-known/jwks.json
    edc.oauth.public.key.alias={{ .Values.dataspace.publicKeyAliasTier1 }}
    edc.oauth.token.url={{ .Values.security.dapsUrl }}/token
    
    edc.dataplane.selector.agentplane.url=http://tiera-data-plane:8082/
    edc.dataplane.selector.agentplane.sourcetypes=cx-common:Protocol?w3c:http:SPARQL,HttpData
    edc.dataplane.selector.agentplane.destinationtypes=HttpProxy
    edc.dataplane.selector.agentplane.properties={ "publicApiUrl": "https://{{ .Values.ingress.host }}/tiera-edc-data/{{ .Values.dataspace.bpnTier1 }}/data/" }
    
    edc.transfer.proxy.endpoint=https://{{ .Values.ingress.host }}/tiera-edc-data/{{ .Values.dataspace.bpnTier1 }}
    edc.transfer.proxy.token.signer.privatekey.alias={{ .Values.dataspace.privateKeyAliasTier1 }}
    edc.transfer.proxy.token.verifier.publickey.alias={{ .Values.dataspace.publicKeyAliasTier1 }}
    edc.transfer.send.retry.limit=0
    edc.negotiation.consumer.send.retry.limit=0
    edc.negotiation.provider.send.retry.limit=0

    edc.vault.hashicorp.url={{ .Values.security.vaultUrl }}
    edc.vault.hashicorp.token={{ .Values.security.vaultToken }}
    edc.vault.hashicorp.timeout.seconds=30
    edc.vault.hashicorp.health.check.enabled=false
    edc.vault.hashicorp.health.check.standby.ok=false
    edc.vault.hashicorp.api.secret.path=/v1/knowledge
    edc.vault.hashicorp.api.health.check.path=/v1/sys/health
  opentelemetry.properties: |-
    otel.javaagent.enabled=false
    otel.javaagent.debug=false
  logging.properties: |-
    .level=FINE
    org.eclipse.dataspaceconnector.level=ALL
    handlers=java.util.logging.ConsoleHandler
    java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
    java.util.logging.ConsoleHandler.level=ALL
    java.util.logging.SimpleFormatter.format=[%1$tY-%1$tm-%1$td %1$tH:%1$tM:%1$tS] [%4$-7s] %5$s%6$s%n
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiera-control-plane
  namespace: {{ .Values.namespace }}
  annotations:
    container.apparmor.security.beta.kubernetes.io/tiera-control-plane: default
spec:
  selector:
    matchLabels:
      app: tiera-control-plane
  template:
    metadata:
      labels:
        app: tiera-control-plane
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 10100
        runAsGroup: 30000
        fsGroup: 30000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - image: tractusx/edc-controlplane-memory-hashicorp-vault:0.4.1
          imagePullPolicy: Always
          name: tiera-control-plane
          securityContext:
            capabilities:
              drop:
                - all
              add: ['NET_BIND_SERVICE']
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8080 # API
            - containerPort: 8081 # OBSERVABILITY
            - containerPort: 8181 # MANAGEMENT
            - containerPort: 8282 # PROTOCOL
            - containerPort: 9999 # CONTROL
            - containerPort: 9998 # METRICS
          env:
            - name:  EDC_FS_CONFIG
              value: /connector-config/configuration.properties
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 512Mi
          startupProbe:
            failureThreshold: 17
            httpGet:
              path: /observability/check/startup
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 4
            httpGet:
              path: /observability/check/liveness
              port: 8081
              scheme: HTTP
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 2
            httpGet:
              path: /observability/check/readiness
              port: 8081
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          volumeMounts:
            - name: control-plane-config
              mountPath: /connector-config
              readOnly: true
            - name: control-plane-config
              mountPath: /app/configuration.properties
              subPath: configuration.properties
              readOnly: true
            - name: control-plane-config
              mountPath: /app/opentelemetry.properties
              subPath: opentelemetry.properties
              readOnly: true
            - name: control-plane-config
              mountPath: /app/logging.properties
              subPath: logging.properties
              readOnly: true
      volumes:
        - name: control-plane-config
          configMap:
            name: tiera-control-plane-config
---
apiVersion: v1
kind: Service
metadata:
  name: tiera-control-plane
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: api
      targetPort: 8080
    - port: 8081
      name: observability
      targetPort: 8081
    - port: 8181
      name: management
      targetPort: 8181
    - port: 8282
      name: ids
      targetPort: 8282
    - port: 9999
      name: control
      targetPort: 9999
    - port: 9998
      name: metrics
      targetPort: 9998
  selector:
    app: tiera-control-plane
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tiera-control-plane-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.issuer }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://knowledge.dev.demo.catena-x.net, http://localhost:3000"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, PUT, POST, DELETE, PATCH, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Host,DNT,X-Api-Key,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization"
    nginx.ingress.kubernetes.io/x-forwarded-prefix: "/tiera-control-plane"
    nginx.org/mergeable-ingress-type: minion
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /tiera-edc-control/{{ .Values.dataspace.bpnTier1 }}/(management)(.*)
            pathType: Prefix
            backend:
              service:
                name: tiera-control-plane
                port:
                  number: 8181
          - path: /tiera-edc-control/{{ .Values.dataspace.bpnTier1 }}/(api/v1/dsp)(.*)
            pathType: Prefix
            backend:
              service:
                name: tiera-control-plane
                port:
                  number: 8282
          - path: /tiera-edc-control/{{ .Values.dataspace.bpnTier1 }}/(observability/check)(.*)
            pathType: Prefix
            backend:
              service:
                name: tiera-control-plane
                port:
                  number: 8081
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tiera-data-plane-config
  namespace: {{ .Values.namespace }}
data:
  configuration.properties: |-
    web.http.default.port=8082
    web.http.default.path=/api
    web.http.public.port=8185
    web.http.public.path=/data
    web.http.callback.port=8187
    web.http.callback.path=/callback
    web.http.control.port=9999
    web.http.control.path=/api/dataplane/control
        
    tractusx.api.observability.allow-insecure=true
    web.http.observability.port=8083
    web.http.observability.path=/observability
 
    tractusx.auth.agent.type=jwt
    tractusx.auth.agent.publickey=https://centralidp.int.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/certs
    tractusx.auth.agent.register=true
    tractusx.auth.agent.checkexpiry=false
    tractusx.auth.agent.paths=default
  
    edc.api.auth.key={{ .Values.security.xApiKey }}
    edc.participant.id=BPNL00000003CPIY
    
    cx.agent.callback=http://tiera-data-plane:8187/callback/endpoint-data-reference
    cx.agent.controlplane.protocol=http://tiera-control-plane:8282
    cx.agent.controlplane.management=http://tiera-control-plane:8181/management/v2
    cx.agent.asset.file=dataspace.ttl
    cx.agent.dataspace.synchronization=-1
    cx.agent.dataspace.remotes=
    
    edc.dataplane.token.validation.endpoint=http://tiera-control-plane:9999/control/token
    edc.core.retry.retries.max= 0
    
    edc.vault.hashicorp.url={{ .Values.security.vaultUrl }}
    edc.vault.hashicorp.token={{ .Values.security.vaultToken }}
    edc.vault.hashicorp.timeout.seconds=30
    edc.vault.hashicorp.health.check.enabled=false
    edc.vault.hashicorp.health.check.standby.ok=false
    edc.vault.hashicorp.api.secret.path=/v1/knowledge
    edc.vault.hashicorp.api.health.check.path=/v1/sys/health
  opentelemetry.properties: |-
    otel.javaagent.enabled=false
    otel.javaagent.debug=false
  logging.properties: |-
    .level=FINE
    org.eclipse.dataspaceconnector.level=ALL
    handlers=java.util.logging.ConsoleHandler
    java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
    java.util.logging.ConsoleHandler.level=ALL
    java.util.logging.SimpleFormatter.format=[%1$tY-%1$tm-%1$td %1$tH:%1$tM:%1$tS] [%4$-7s] %5$s%6$s%n
  agent.ttl: |-
{{- .Files.Get .Values.dataspace.config | nindent 4 }}
  dataspace.ttl: |-
{{- .Files.Get .Values.dataspace.ontology | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiera-data-plane
  namespace: {{ .Values.namespace }}
  annotations:
    container.apparmor.security.beta.kubernetes.io/tiera-data-plane: default
spec:
  selector:
    matchLabels:
      app: tiera-data-plane
  template:
    metadata:
      labels:
        app: tiera-data-plane
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 10100
        runAsGroup: 30000
        fsGroup: 30000
        seccompProfile:
            type: RuntimeDefault
      containers:
        - image: ghcr.io/catenax-ng/product-agents-edc/agentplane-hashicorp:1.9.3-SNAPSHOT
          imagePullPolicy: Always
          name: tiera-data-plane
          securityContext:
            capabilities:
              drop:
                - all
              add: ['NET_BIND_SERVICE']
            allowPrivilegeEscalation: false   
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8082 # API
            - containerPort: 8083 # OBSERVABILITY
            - containerPort: 8185 # PUBLIC
            - containerPort: 8187 # AGREEMENT CALLBACK
            - containerPort: 9999 # CONTROL
          env:
            - name:  EDC_FS_CONFIG
              value: /connector-config/configuration.properties
          resources:
           requests:
            cpu: 500m
            memory: 512Mi
           limits:
            cpu: 500m
            memory: 512Mi
          startupProbe:
            failureThreshold: 17
            httpGet:
              path: /observability/check/startup
              port: 8083
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 4
            httpGet:
              path: /observability/check/liveness
              port: 8083
              scheme: HTTP
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 2
            httpGet:
              path: /observability/check/readiness
              port: 8083
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5          
          volumeMounts:
            - name: tiera-data-plane-config
              mountPath: /connector-config
              readOnly: true
            - name: tiera-data-plane-config
              mountPath: /app/configuration.properties
              subPath: configuration.properties
              readOnly: true
            - name: tiera-data-plane-config
              mountPath: /app/opentelemetry.properties
              subPath: opentelemetry.properties
              readOnly: true
            - name: tiera-data-plane-config
              mountPath: /app/logging.properties
              subPath: logging.properties
              readOnly: true
            - name: tiera-data-plane-config
              mountPath: /app/agent.ttl
              subPath: agent.ttl
              readOnly: true
            - name: tiera-data-plane-config
              mountPath: /app/dataspace.ttl
              subPath: dataspace.ttl
              readOnly: true
      volumes:
        - name: tiera-data-plane-config
          configMap:
            name: tiera-data-plane-config
---
apiVersion: v1
kind: Service
metadata:
  name: tiera-data-plane
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 8082
      name: api
      targetPort: 8082
    - port: 8083
      name: observability
      targetPort: 8083
    - port: 8185
      name: public
      targetPort: 8185
    - port: 8186
      name: callback
      targetPort: 8187
    - port: 9999
      name: control
      targetPort: 9999
  selector:
    app: tiera-data-plane
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tiera-data-plane-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.issuer }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://knowledge.dev.demo.catena-x.net, http://localhost:3000"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, PUT, POST, DELETE, PATCH, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Host,DNT,X-Api-Key,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization"
    nginx.ingress.kubernetes.io/x-forwarded-prefix: "/tiera-data-plane"
    nginx.org/mergeable-ingress-type: minion
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /tiera-edc-data/{{ .Values.dataspace.bpnTier1 }}/(data)(.*)
            pathType: Prefix
            backend:
              service:
                name: tiera-data-plane
                port:
                  number: 8185
          - path: /tiera-edc-data/{{ .Values.dataspace.bpnTier1 }}/(api/agent)(.*)
            pathType: Prefix
            backend:
              service:
                name: tiera-data-plane
                port:
                  number: 8082

