edc:
  repo: ghcr.io/catenax-ng/product-knowledge
  version: 0.1.2-KA-SNAPSHOT

version: 0.6.4-SNAPSHOT

dataspace:
  bpnOem: BPNL00000003COJN
  privateKeyAliasOem: "oem-daps-key"
  publicKeyAliasOem: "oem-daps-crt"
  dapsClientIdOem: ""
  bpnTier1: BPNL00000003CPIY
  privateKeyAliasTier1: "tier1-daps-key"
  publicKeyAliasTier1: "tier1-daps-crt"
  dapsClientIdTier1: ""
  bpnCustomer: BPNL00000003CQI9
  privateKeyAliasCustomer: "customer-daps-key"
  publicKeyAliasCustomer: "customer-daps-crt"
  dapsClientIdCustomer: ""
  ontology: resources/dataspace.ttl
  config: resources/agent.ttl

ingress:
  host: knowledge.int.demo.catena-x.net
  oemHost: knowledge-oem.int.demo.catena-x.net
  issuer: letsencrypt-prod

namespace: "product-knowledge"

security:
  htpasswd: ""
  htpasswdtype: ""
  backupsName: ""
  backupsKey: ""
  backupsShare: ""
  authType: ""
  xApiKey: ""
  dapsUrl: "https://daps1.int.demo.catena-x.net"
  vaultClientId: ""
  vaultClientSecret: ""
  vaultName: ""
  vaultTenant: ""
  backendUser: ""
  backendPwd: ""



