name: Build and Collect Reports

on: [push, pull_request]

jobs:
  java:
    name: Java Build and Collect 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Sources
      uses: actions/checkout@v3
    - name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -s settings.xml -B package --file pom.xml
      env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Java Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: 'Java Test Report'
        path: '**/surefire-reports/TEST-*.xml'
        reporter: java-junit
        java-version: 11
  typescript:
    name: TypeScript Build and Collect
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ux

    steps:
    - name: Checkout Sources
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm install -g jest
    - run: npm run init:dev
    - run: npm test
    - name: TypeScript Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: 'TypeScript Test Report'
        path: '**/reports/jest-*.xml'
        reporter: jest-junit