name:  ESLint
on: [push]
jobs:
  eslint_check:
    name: Prepare action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Node Dependencies
        run: |
          cd ux
          npm install
      - name: Test Code Linting
        run: |
          cd ux
          npm run lint