name: Integration Tests

on: workflow_dispatch

jobs:
  run_integration_test:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: https://vault.demo.catena-x.net:443
          role: product-knowledge
          method: jwt
          jwtGithubAudience: sigstore
          secrets: |
              knowledge/oem password | OEM_PASSWORD ;
              knowledge/oem api-key | OEM_EDC_API_KEY ;
